#!/bin/bash
IMG_DIR=/home/songzhuoran/video/video-block-based-acc/davis2016/data/
OUT_DIR=../data

video_gen(){
    mkdir -p $OUT_DIR/video
    mkdir -p $OUT_DIR/mvs

    rm -rf $OUT_DIR/video/*
    rm -rf $OUT_DIR/mvs/*

    # echo "Warning: Next step will run '$ rm -rf Video & mvs' command. "
    # read -p "Continue (y/n)?" CONT
    # if [ "$CONT" = "y" ]; then
    #     rm -rf $OUT_DIR/video/*
    #     rm -rf $OUT_DIR/mvs/*
    # else
    #     echo ERROR: You refused to delete Video\'s directory.
    #     exit
    # fi

    for class_str in $IMG_DIR/*; do
        class=${class_str##*/}
        echo ${class}\'s video start producing ...
        ffmpeg -i $IMG_DIR/$class/%5d.jpg -vcodec libx265 -x265-params lossless=1 tmp.mp4
        ffmpeg -i tmp.mp4 -vcodec libx265 -x265-params lossless=1 $OUT_DIR/video/$class.mp4 > $OUT_DIR/mvs/$class.csv
        rm tmp.mp4
        echo ${class}\'s video done successfully. 
    done
    echo "Video & mvs generation step success."
}

idx_gen(){
    mkdir -p $OUT_DIR/idx/p
    mkdir -p $OUT_DIR/idx/b

    rm -rf $OUT_DIR/idx/p/*
    rm -rf $OUT_DIR/idx/b/*  
    # echo "Warning: Next step will run '$ rm -rf Index' command. "
    # read -p "Continue (y/n)?" CONT
    # if [ "$CONT" = "y" ]; then
    #     rm -rf $OUT_DIR/idx/p/*
    #     rm -rf $OUT_DIR/idx/b/*
    # else
    #     echo ERROR: You refused to delete Index\'s directory.
    #     exit
    # fi

    for class_str in $IMG_DIR/*; do
	class=${class_str##*/}
	ffprobe -select_streams v -show_frames -show_entries frame=pict_type -of csv $OUT_DIR/video/$class.mp4 | grep -n [IP] | cut -d ':' -f 1 > $OUT_DIR/idx/p/$class
	ffprobe -select_streams v -show_frames -show_entries frame=pict_type -of csv $OUT_DIR/video/$class.mp4 | grep -n [B] | cut -d ':' -f 1 > $OUT_DIR/idx/b/$class
    done
    echo "Index generation step success."
}

bframe_gen(){
    rm -rf $OUT_DIR/train/bframe/*
    # echo "Warning: Next step will run '$ rm -rf Bframe' command. "
    # read -p "Continue (y/n)?" CONT
    # if [ "$CONT" = "y" ]; then
    #     rm -rf $OUT_DIR/train/bframe/*
    # else
    #     echo ERROR: You refused to delete Bframe\'s directory.
    #     exit
    # fi
    
    for class_str in $IMG_DIR/*; do
        class=${class_str##*/}
	cd ../code
	python bframe_gen.py $class
	echo "$class generation done. "
    cd ../util
    done
}

#need to modify
#video_gen
#idx_gen
bframe_gen
