#!/bin/bash

Bframe_dir=/home/songzhuoran/video/video-block-based-acc/mapping-propa
dst_dir=/home/songzhuoran/video/video-block-based-acc/block_result

val_names="cows scooter-black horsejump-high parkour paragliding-launch kite-surf breakdance drift-straight goat bmx-trees libby motocross-jump drift-chicane dance-twirl blackswan car-roundabout car-shadow dog soapbox camel"


for dir_name in $val_names; do
    echo $dir_name
    mkdir -p $dst_dir/$dir_name
    for image in $Bframe_dir/$dir_name/*; do
	image_name=${image##*/}
	echo image_name=$image_name
	echo input=$image
	echo output=$dst_dir/$dir_name/$image_name
	cd ../code
	python predict_v2.py $image $dst_dir/$dir_name/$image_name
	cd ../util
	# exit
    done
done
